# Generated by Django 4.2 on 2025-02-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wastage", "0002_wastage_name_ee_wastage_name_ru_alter_wastage_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wastage",
            options={"verbose_name": "Отходы", "verbose_name_plural": "Отходы"},
        ),
    ]
