# Generated by Django 4.2 on 2025-02-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "container",
            "0007_container_description_ee_container_description_ru_and_more",
        ),
        ("wastage", "0003_alter_wastage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.container",
                    ),
                ),
                (
                    "wastage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wastage.wastage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Горячие предложения",
                "verbose_name_plural": "Горячие предложения",
            },
        ),
    ]
