# Generated by Django 4.2 on 2025-02-07 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wastage", "0003_alter_wastage_options"),
        ("container", "0004_alter_container_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_date", models.DateField()),
                ("end_time", models.TimeField()),
                ("address", models.CharField(max_length=500)),
                ("extra_km", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_extra_km",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "price_total_extra_km",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "included_weight",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("extra_weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_weight", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_extra_weight",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("volume", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("customer", models.CharField(max_length=255)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.container",
                    ),
                ),
                (
                    "wastage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wastage.wastage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
