# Generated by Django 4.2 on 2025-02-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="included_days",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="price_extra_day",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_days",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_price_extra_day",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
    ]
