# Generated by Django 4.2 on 2025-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_included_days_order_price_extra_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price_no_vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
