# Generated by Django 4.2 on 2025-02-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_price_no_vat_order_vat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="price_total",
            new_name="total_price",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="price_total_extra_km",
            new_name="total_price_extra_km",
        ),
        migrations.AddField(
            model_name="order",
            name="total_price_extra_weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
