# Generated by Django 4.2 on 2025-02-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wastage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("volume", models.DecimalField(decimal_places=2, max_digits=3)),
                ("max_weight", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "included_weight",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_extra_weight",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "wastage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wastage.wastage",
                    ),
                ),
            ],
        ),
    ]
