# Generated by Django 4.2 on 2025-02-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="name_ee",
            field=models.CharField(default="hola", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="container",
            name="name_ru",
            field=models.CharField(default="hola", max_length=255),
            preserve_default=False,
        ),
    ]
