# Generated by Django 4.2 on 2025-02-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0002_container_name_ee_container_name_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="included_weight",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="container",
            name="max_weight",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="container",
            name="volume",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
