# Generated by Django 4.2 on 2025-02-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0003_alter_container_included_weight_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="container",
            options={"verbose_name": "Контейнер", "verbose_name_plural": "Контейнера"},
        ),
    ]
