# Generated by Django 4.2 on 2025-02-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0004_alter_container_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="max_volume",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="container",
            name="price_extra_volume",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
