# Generated by Django 4.2 on 2025-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0006_container_included_days_container_price_extra_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="description_ee",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="container",
            name="description_ru",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="container",
            name="price_extra_mileage",
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=10),
            preserve_default=False,
        ),
    ]
